### PR TITLE
Add a plugin for flv streaming.

### PR DESCRIPTION
**Pull request by mizzy**
This plugin is for handling flv streaming and uses new hooks added by the commit ddb49e3.

@dormando said "It would be cool to have an example plugin for streaming FLV :)" in pullreq #1,
so I send this pullreq.

Thanks.

### CODE REVIEW

**Comment by dormando** [comment]
Mind writing a couple lines of quick usage POD at the top? We're trying to be better about documenting as well :)

Thanks for doing this so quickly! I will merge it immediately

**Comment by mizzy** [comment]
Thanks for your comment.

I see.I will write the usage.Please wait a moment.

**Comment by mizzy** [comment]
I've added simple usage. Please check it.

Thanks.

**Comment by dormando** [comment]
Looks good enough, thank you very much! I've merged and pushed.

I might write an example application for MogileFS later using this plugin. The question comes up occasionally. thanks again :)

**Comment by mizzy** [comment]
Thanks for merging and pushing.

Questions are welcome :)

**Pull request closed without merging**
