### PR TITLE
Add path rewriting to Vpaths plugin

### PR DESCRIPTION
**Pull request by zorkian**
When matching a path, allow the plugin to also do URI rewriting by appending that to the configuration line:

```
VPATH ^/nagios/(.+)$ = service /cgi-bin/nagios3/\0
```

That will transparently rewrite requests for "/nagios/foo" to "/cgi-bin/nagios3/foo" before sending them down to the service named 'service'.

### CODE REVIEW

**Comment by abh** [comment]
Nice feature, terrible syntax, I think.  :-)  At least it'll be hard to extend it...

Would it make sense to have it be a separate keyword to rewrite paths?

**Comment by zorkian** [comment]
Hmm... my concern there would be that it's not obvious this all works on the same queue of paths:

`VPATH blah = service
VPATHR blah2 = service rewrite
VPATH blah3 = service`

I agree the syntax is bad.  Maybe one of these seems more appropriate?

`VPATH blah => rewrite = service
VPATH blah: rewrite = service
VPATH service blah = rewrite
VPATH [service] blah = rewrite`

I'm somewhat against random characters in the string, so I'd vote somewhat against the colons/brackets.  The arrow is interesting, maybe... but it's not really a 'standard' configuration option.

Maybe we should just force people to either use VPATH or VPATH_REWRITE and then have separate syntaxes.  That way people can choose which one they want to use and make it obvious that it's different.

Oh!  Or maybe:

`VPATH uri = service REWRITE TO new_uri`

This goes with our natural language configuration file approach and seems to be probably the best option.  What do you think?

**Comment by abh** [comment]
> `VPATH uri = service REWRITE TO new_uri`

I like it!  Dormando?

**Comment by zorkian** [comment]
Oh, re: the separate plugin comment ... yes.  I have a separate branch going where I'm working on a general mod_rewrite style plugin that will let you do more complicated tricks and redirects and the like.  That's going to take a bit longer and I wanted the functionality sooner, so I put it in Vpaths.

I'm happy with leaving this as a very very simple plugin and just putting all of the effort into the Rewrite plugin.  That's reasonable.  I can see arguments either way

**Comment by dormando** [comment]
+1 on REWRITE TO syntax. care to update it so we can test/merge?

Adding the rewrite stuff to the end is definitely not very readable. Thanks! Sorry it took so long to look at this.

**Comment by yannk** [comment]
Hey guys, stumble upon this and though I'd share this extension of VPath:

https://github.com/yannk/perlbal-plugin-router/blob/master/lib/Perlbal/Plugin/Router.pm

**Pull request closed without merging**
